name: Black code formatting check

on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Setup poetry
        uses: SG60/setup-poetry@v1
      - run: poetry install --only formatting
      - run: poetry run black . --check --verbose