# export CUDA_VISIBLE_DEVICES=0
python -u src/train.py \
    --is_training 1 \
    --model_id "BSIformer_classification_BSIT_samplewavelet_relu_cut1_emb32_channelemb_linearattn2_batchstand_etf+proj" \
    --model "BSIformerT" \
    --task "Classification" \
    --dataset "BSIsamplewavelet" \
    --batch_size 512 \
    --embed_dim 32 \
    --hidden_dim 128 \
    --num_heads 2 \
    --num_layers 2 \
    --num_t_pints 768 \
    --num_patches 10 \
    --num_cut 1 \
    --n_epochs 150 \
    --early_stop 40 \
    --n_classes 4 \
    --plot_epoch 30 \
    --learning_rate 3e-4 \
    --weight_decay 2e-4 \
    --dropout 0.1 \
    --aug_variance 0.01 \
    --use_gpu True \
    --N_WORKERS 16 \
    --gpu "cuda:0" \
    --scaling \
    --mask_rate 0.0 \
    --etf \
